### ISSUE TITLE
SodaHub (Social Data Hub): Own your data, publish everywhere

### ISSUE THREAD

**Issue by victorneo** [fix-the-internet/mozilla-builders#16]
**Problem Statement**
Most distributed or decentralized social networks do not successfully convert folks from mainstream social networks to join them as their friends or family are not in the new network. For many of us, this means that we continue to have to maintain our accounts on these networks while they continue to own our data.

The idea here is not to wait for a decentralized social network or publishing platform today to achieve world dominance before we own our data - let's own our data on our own terms, and publish them to where we want.

**Idea**
SodaHub, short for Social Data Hub is an idea to be a self-owned platform that allows you to own your content (text, images, video) and allows you to publish them to other social networks. This allows you to continue to publish your content on supported social networks or publishing platforms, while you own the data without having to deal with exports.

SodaHub will support decentralized social networks as first-class citizens, such as ActivityPub, OStatus, and more.

**Challenges**
The primary challenges for this project are:
- User adoption: "why should I use this?"
- Publishing APIs: do big-tech social networks support publishing?

**We should not be inventing a new standard** as existing protocols and standards for decentralized networks already exist and works (eg. Mastodon for ActivityPub with Fediverse federation).

If you are keen, please reply to this issue, or reach out to me on Mozilla Builder's Slack (Victor Neo).

**Comment by nitss007** [comment]
Hi Victor,

I am not sure, if you have already paired up , but i find this project very interesting and would like to contribute to it. 
I am good in backend (java, python) and a started in frontend..

Please ping me back or connect with me at https://www.linkedin.com/in/nitishsharma1/

**Comment by aviralch** [comment]
Hi Victor, 

This sounds like a really good and exciting project. I would really like to team up .
my email is : aviral@terpmail.umd.edu 
I know java python, flask, and have some experience with frontend

**Comment by sanaa-sys** [comment]
Hi Victor
I am also interested in this project if you are still looking for new members. Please fell free to message me in LinkedIn: https://www.linkedin.com/in/ayesha-ali-481106198/
My skillset includes Python, C++,C and some front-end dev

**Comment by dynamoRando** [comment]
Possibly tangential to your aspirations - https://solid.mit.edu/

**Comment by victorneo** [comment]
@nitss007 @aviralch @sanaa-sys Thanks for reaching out. I'll checking in with a couple of folks who have reached out on Slack and will get back to you.

@dynamoRando Yup, I am aware of Solid and its spec can be a possible means to storage and enable data access in the future. It's quite exciting for me so I'm following their spec updates quite closely.

**Comment by rebelcode-xr** [comment]
Hi @victorneo, I envisioned something really similar to your idea :)

**OPEN SOCIALS FIRST APPROACH**
In [XR Italy](http://xritaly.it/) we're developing a different approach to communicate our broadcasting channels: https://extinctionrebellion.it/xr-magazine/2020/03/12/non-c%C3%A8-alternativa-a-facebook-vi-presentiamo-i-social-ribelli/
We give priority to openness so the mainstream social are a secondary option inside a submenu:
![image](https://user-images.githubusercontent.com/63522951/83972472-99851d80-a8e0-11ea-8aee-b7b5da360d6c.png)

**CHANGE THE NARRATIVE OUTSIDE AND INSIDE PROJECTS**
This is the kind of UI/UX things (there're many others, especially inside the socials) that could be implemented inside a platform to give users more awareness about what we should promote and what should be a secondary option. This, of course, is not enough because we lose a lot of time managing AI based socials and we don't have enough energy to fully focus on more ethical and open platforms (Telegram and Fediverse are our main options due to adoption rate).
![image](https://user-images.githubusercontent.com/63522951/84377568-136c1e00-abe3-11ea-8091-85f61cfc483d.png)

**WE NEED TOOLS TO HELP US AND NOT THEM**
We were thinking about building a piece of software that could change the public UI/UX (prioritising open solutions will teach people they can avoid the "promotion" part [taking just advantage of the presence](https://stallman.org/facebook-presence.html)) and managing socials in a different way (teaching "by doing" a new approach to web marketing), all in one place (integrating AP, Telegram and continue posting on Fb & co.). Two solutions came to our minds: something like what you mentioned and a plug-in.
![image](https://user-images.githubusercontent.com/63522951/84377457-e4ee4300-abe2-11ea-825e-c1fa94a44acb.png)


**THE WP PLUG-IN IDEA**
In terms of "scaling fast and easily" we though that a **WordPress plugin** might be a solution that could be easy to implement and reach a wider audience ([35% of all websites run WP!!!](https://kinsta.com/wordpress-market-share/)). This could be a parallel project, using same libraries, so we could have both: a new WP plugin to spread the POSSE approach (less efforts) and a new federated social (more efforts)! :)
![image](https://user-images.githubusercontent.com/63522951/84377492-f0da0500-abe2-11ea-88f3-488b04e7c8b7.png)

**USEFUL LINKS**
https://stallman.org/facebook-presence.html
https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps
https://datatransferproject.dev/
